export const APP = {
  SET_BUILD: 'APP_SET_BUILD'
};

export const USER = {
  AJAX_BEGIN: 'USER_AJAX_BEGIN',
  AJAX_END: 'USER_AJAX_END',
  LOGIN: 'USER_LOGIN',
  LOGOUT: 'USER_LOGOUT'
};

export const PROFILE = {
  AJAX_BEGIN: 'PROFILE_AJAX_BEGIN',
  AJAX_END: 'PROFILE_AJAX_END',
  FETCH_SUCCESS: 'PROFILE_FETCH_SUCCESS',
};

export const TAGS = {
  AJAX_BEGIN: 'TAGS_AJAX_BEGIN',
  AJAX_END: 'TAGS_AJAX_END',
  FETCH_SUCCESS: 'TAGS_FETCH_SUCCESS',
};

export const SNIPPETS = {
  CLEAR_ALL: 'SNIPPETS_CLEAR_ALL',
  FETCH_BEGIN: 'SNIPPETS_FETCH_BEGIN',
  FETCH_END: 'SNIPPETS_FETCH_END',
  FETCH_ALL: 'SNIPPETS_FETCH_ALL',
  FETCH_BY_SEARCH: 'SNIPPETS_FETCH_BY_SEARCH',
  CREATE: 'SNIPPETS_CREATE',
  UPDATE: 'SNIPPETS_UPDATE',
  DELETE: 'SNIPPETS_DELETE',
  SORT_BY: 'SNIPPETS_SORT_BY',
};
