export const USER = {
  LOGIN: 'USER_LOGIN',
  LOGOUT: 'USER_LOGOUT'
};

export const SNIPPETS = {
  FETCH_ALL: 'SNIPPETS_FETCH_ALL',
  CREATE: 'SNIPPETS_CREATE',
  UPDATE: 'SNIPPETS_UPDATE',
  DELETE: 'SNIPPETS_DELETE',
};
